apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:8.0.44-debian
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: B4teau123!
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
